# @package _group_

common:
  fp16: true
  fp16_scale_tolerance: 0.1   # alleviate fp16 overflow issue
  log_format: json
  log_interval: 200
  seed: 1234
  tensorboard_logdir: tblog

checkpoint:
  save_dir: ???
  save_interval: 1
  keep_last_epochs: 4
  save_interval_updates: 10000
  keep_interval_updates: -1
  keep_interval_updates_pattern: 10000
  # no_epoch_checkpoints: true

distributed_training:
  ddp_backend: no_c10d
  distributed_backend: 'nccl'
  distributed_port: -1
  distributed_world_size: 128
  nprocs_per_node: 8
  find_unused_parameters: true

task:
  _name: joint_sc2t_pretraining
  data: ???
  label_dir: ???
  labels: ???
  label_rate: ${model.label_rate}
  store_labels: true
  sample_rate: 16000
  max_sample_size: 250000
  min_sample_size: 32000
  pad_audio: false
  random_crop: true
  normalize: true # must be consistent with extractor
  add_decoder_target: true
  text_cfg:
    seed: ${common.seed}
    text_data: ???
    data_config: config.yaml
    sample_break_mode: eos
    tokens_per_sample: 1024
    shorten_method: "random_crop"
    text_maxtokens_ratio: 1.4

dataset:
  num_workers: 6
  max_tokens: 900000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: ${checkpoint.save_interval}
  validate_interval_updates: ${checkpoint.save_interval_updates}
  required_batch_size_multiple: 2

criterion:
  _name: speechut_criterion
  pred_masked_weight: 1.0
  pred_nomask_weight: 0.0
  loss_weights: [10,]
  label_smoothing: 0.1
  u2t_ed_weight: 0.1
  u2t_ctc_weight: 0.1
  text_mum_weight: 0.5

optimization:
  max_update: 400000
  lr: [0.0005]
  clip_norm: 1.0

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000
  end_learning_rate: 0.00015  # for future longger pre-training, e.g. 600K step

model:
  _name: speechut
  label_rate: ???
  encoder_embed_dim: 1024
  encoder_ffn_embed_dim: 4096
  skip_masked: false
  skip_nomask: false
  mask_prob: 0.80
  extractor_mode: layer_norm
  conv_feature_layers: '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2'
  final_dim: 768
  activation_fn: "gelu"
  encoder_layers: 12
  encoder_attention_heads: 16
  encoder_layerdrop: 0.0
  dropout_input: 0.0
  dropout_features: 0.0
  dropout: 0.0
  attention_dropout: 0.0
  layer_norm_first: true
  feature_grad_mult: 1.0
  untie_final_proj: true
  activation_dropout: 0.0
  use_rel_pos_enc: true
  add_unit_encoder: true
  add_text_ctc: true
  mask_u2t: false
  mix_with_unit: true
  add_decoder: true
  reset_decoder_embedding_config: true
  scaling_for_att: 32   # alleviate fp16 overflow issue
  text_transformer:
    activation_fn: ${model.activation_fn}
    dropout: ${model.dropout}
    attention_dropout: ${model.attention_dropout}
    activation_dropout: ${model.activation_dropout}
    max_source_positions: 3000
    max_target_positions: 3000
    no_scale_embedding: true
    layernorm_embedding: true
    no_token_positional_embeddings: true
    share_decoder_input_output_embed: false
    encoder:
      embed_dim: 1024
      ffn_embed_dim: 4096
      layers: 12
      attention_heads: 16
      normalize_before: false
      learned_pos: true
      layerdrop: ${model.encoder_layerdrop}
    decoder:
      layerdrop: 0.1
      embed_dim: 768
      ffn_embed_dim: 3072
      layers: 6
      attention_heads: 12
      normalize_before: false
      learned_pos: false
      output_dim: 768

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
